// frontend/src/pages/PlanVisualizer.tsx
import React, { useState, useEffect } from 'react';
import {
  Card,
  Table,
  Select,
  Button,
  Space,
  Typography,
  Drawer,
  Descriptions,
  Tag,
  Alert,
} from 'antd';
import { EyeOutlined, BranchesOutlined } from '@ant-design/icons';
import Tree from 'react-d3-tree';
import { apiService } from '@/services/api';
import type { CollectionList, SQLExecutionRecord, PlanDetail, TreeNode } from '@/types';

const { Title } = Typography;
const { Option } = Select;

const PlanVisualizer: React.FC = () => {
  const [collections, setCollections] = useState<CollectionList | null>(null);
  const [selectedCollection, setSelectedCollection] = useState<string>('');
  const [plans, setPlans] = useState<SQLExecutionRecord[]>([]);
  const [selectedPlan, setSelectedPlan] = useState<PlanDetail | null>(null);
  const [treeData, setTreeData] = useState<TreeNode[]>([]);
  const [drawerVisible, setDrawerVisible] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>('');
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [total, setTotal] = useState(0);

  // 加载集合列表
  useEffect(() => {
    const loadCollections = async () => {
      try {
        const data = await apiService.getCollections();
        setCollections(data);
        if (data.collections.length > 0) {
          setSelectedCollection(data.collections[0]);
        }
      } catch (err) {
        setError('加载集合列表失败');
      }
    };
    loadCollections();
  }, []);

  // 加载计划列表
  useEffect(() => {
    if (selectedCollection) {
      loadPlans();
    }
  }, [selectedCollection, currentPage]);

  const loadPlans = async () => {
    setLoading(true);
    setError('');
    try {
      const data = await apiService.getPlans(selectedCollection, currentPage, pageSize);
      setPlans(data.items);
      setTotal(data.total);
    } catch (err) {
      setError('加载计划列表失败');
    } finally {
      setLoading(false);
    }
  };

  const handlePageChange = (page: number, size?: number) => {
    setCurrentPage(page);
    if (size && size !== pageSize) {
      setPageSize(size);
    }
  };

  const handleShowSizeChange = (current: number, size: number) => {
    setPageSize(size);
    setCurrentPage(1);
  };

  const handleCollectionChange = (value: string) => {
    setSelectedCollection(value);
    setCurrentPage(1);
  };

  const handleViewPlan = async (record: SQLExecutionRecord) => {
    try {
      console.log('正在获取执行计划详情，ID:', record._id, '集合:', selectedCollection);
      const planDetail = await apiService.getPlanDetail(record._id, selectedCollection);
      console.log('执行计划详情获取成功:', planDetail);
      setSelectedPlan(planDetail);
      
      // 转换执行计划为树状图数据
      const treeNodes = convertPlanToTree(planDetail);
      setTreeData(treeNodes);
      
      setDrawerVisible(true);
    } catch (err: any) {
      console.error('获取执行计划详情失败:', err);
      if (err.response) {
        console.error('错误响应状态:', err.response.status);
        console.error('错误响应数据:', err.response.data);
      }
      setError(`获取执行计划详情失败: ${err.response?.data?.detail || err.message || '未知错误'}`);
    }
  };

  // 转换执行计划为树状图数据
  const convertPlanToTree = (plan: PlanDetail): TreeNode[] => {
    const nodeMap = new Map<string, TreeNode>();
    
    // 创建所有节点
    plan.nodes.forEach(node => {
      const nodeId = `node_${node.raw_data._id || Math.random().toString(36).substr(2, 9)}`;
      const treeNode: TreeNode = {
        name: `${node.node_type}`,
        attributes: {
          '实际时间': node.actual_total_time?.toFixed(2) + 'ms' || 'N/A',
          '实际行数': node.actual_rows?.toString() || 'N/A',
          '循环次数': node.loops?.toString() || 'N/A',
          '缓存命中': node.shared_hit_blocks?.toString() || 'N/A',
          '缓存读取': node.shared_read_blocks?.toString() || 'N/A',
        },
      };
      nodeMap.set(nodeId, treeNode);
    });

    // 建立父子关系
    const treeRoots: TreeNode[] = [];
    plan.nodes.forEach((node, index) => {
      const nodeId = `node_${index}`;
      const treeNode = nodeMap.get(nodeId)!;
      
      if (node.parent) {
        const parentNode = nodeMap.get(node.parent);
        if (parentNode) {
          if (!parentNode.children) parentNode.children = [];
          parentNode.children.push(treeNode);
        }
      } else {
        treeRoots.push(treeNode);
      }
    });

    return treeRoots;
  };

  // 为节点计算颜色
  const getNodeColor = (node: any) => {
    const time = node.attributes?.['实际时间'];
    if (time && time !== 'N/A') {
      const timeMs = parseFloat(time);
      if (timeMs > 100) return '#F87171'; // 红色 - 高耗时
      if (timeMs > 50) return '#FBBF24'; // 黄色 - 中等耗时
      return '#34D399'; // 绿色 - 低耗时
    }
    return '#388BFF'; // 默认蓝色
  };

  const columns = [
    {
      title: 'SQL内容',
      dataIndex: 'sql_content',
      key: 'sql_content',
      width: '40%',
      render: (text: string) => (
        <div style={{ 
          maxWidth: '400px', 
          overflow: 'hidden', 
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap' 
        }}>
          {text}
        </div>
      ),
    },
    {
      title: '执行时间',
      dataIndex: 'execution_time_ms',
      key: 'execution_time_ms',
      width: '15%',
      render: (time: number) => `${time.toFixed(2)}ms`,
      sorter: (a: SQLExecutionRecord, b: SQLExecutionRecord) => 
        a.execution_time_ms - b.execution_time_ms,
    },
    {
      title: '返回行数',
      dataIndex: 'row_count',
      key: 'row_count',
      width: '15%',
      sorter: (a: SQLExecutionRecord, b: SQLExecutionRecord) => 
        a.row_count - b.row_count,
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: '10%',
      render: (status: string) => (
        <Tag color={status === 'success' ? 'green' : status === 'error' ? 'red' : 'orange'}>
          {status === 'success' ? '成功' : status === 'error' ? '失败' : '未知'}
        </Tag>
      ),
    },
    {
      title: '文件名',
      dataIndex: 'file_name',
      key: 'file_name',
      width: '15%',
    },
    {
      title: '操作',
      key: 'action',
      width: '5%',
      render: (_: any, record: SQLExecutionRecord) => (
        <Button
          type="link"
          icon={<EyeOutlined />}
          onClick={() => handleViewPlan(record)}
        >
          查看
        </Button>
      ),
    },
  ];

  return (
    <div style={{ padding: '0' }}>
      <div style={{ marginBottom: '24px' }}>
        <Title level={2} style={{ margin: 0 }}>
          执行计划可视化
        </Title>
        <p style={{ color: '#A1A1AA', marginTop: '8px' }}>
          查看和分析SQL查询执行计划
        </p>
      </div>

      {/* 集合选择器 */}
      <Card style={{ marginBottom: '24px' }}>
        <Space>
          <span>选择数据集合:</span>
          <Select
            value={selectedCollection}
            onChange={handleCollectionChange}
            style={{ width: 200 }}
            disabled={!collections}
          >
            {collections?.collections.map(collection => (
              <Option key={collection} value={collection}>
                {collection}
              </Option>
            ))}
          </Select>
        </Space>
      </Card>

      {error && (
        <Alert
          message="错误"
          description={error}
          type="error"
          style={{ marginBottom: '24px' }}
        />
      )}

      {/* 计划列表 */}
      <Card>
        <Table
          columns={columns}
          dataSource={plans}
          rowKey="_id"
          loading={loading}
          pagination={{
            current: currentPage,
            pageSize: pageSize,
            total: total,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total, range) => `第 ${range[0]}-${range[1]} 条，共 ${total} 条`,
            onChange: handlePageChange,
            onShowSizeChange: handleShowSizeChange,
            pageSizeOptions: ['10', '20', '50', '100'],
          }}
        />
      </Card>

      {/* 执行计划详情抽屉 */}
      <Drawer
        title={
          <Space>
            <BranchesOutlined />
            执行计划详情
          </Space>
        }
        placement="right"
        size="large"
        onClose={() => setDrawerVisible(false)}
        open={drawerVisible}
      >
        {selectedPlan && (
          <>
            {/* 基本信息 */}
            <Card title="基本信息" style={{ marginBottom: '16px' }}>
              <Descriptions column={1} size="small">
                <Descriptions.Item label="SQL内容">
                  <div style={{ 
                    maxHeight: '100px', 
                    overflow: 'auto',
                    fontFamily: 'monospace',
                    fontSize: '12px',
                    background: '#f5f5f5',
                    padding: '8px',
                    borderRadius: '4px'
                  }}>
                    {selectedPlan.sql_content}
                  </div>
                </Descriptions.Item>
                <Descriptions.Item label="执行时间">
                  <Tag color="blue">{selectedPlan.execution_time_ms.toFixed(2)}ms</Tag>
                </Descriptions.Item>
                <Descriptions.Item label="返回行数">
                  <Tag color="green">{selectedPlan.row_count}</Tag>
                </Descriptions.Item>
                <Descriptions.Item label="状态">
                  <Tag color={selectedPlan.status === 'success' ? 'green' : 'red'}>
                    {selectedPlan.status === 'success' ? '成功' : '失败'}
                  </Tag>
                </Descriptions.Item>
              </Descriptions>
            </Card>

            {/* 执行计划树状图 */}
            <Card title="执行计划树状图">
              {treeData.length > 0 ? (
                <div style={{ width: '100%', height: '500px', border: '1px solid #E5E7EB' }}>
                  <Tree
                    data={treeData}
                    orientation="vertical"
                    translate={{ x: 400, y: 50 }}
                    separation={{ siblings: 1, nonSiblings: 1.5 }}
                    nodeSize={{ x: 200, y: 100 }}
                    zoom={0.8}
                    enableLegacyTransitions
                    renderCustomNodeElement={(rd3tProps) => {
                      const { nodeDatum, toggleNode } = rd3tProps;
                      const fillColor = getNodeColor(nodeDatum);
                      
                      return (
                        <g>
                          <circle
                            r={12}
                            fill={fillColor}
                            stroke="#fff"
                            strokeWidth={2}
                            onClick={() => toggleNode()}
                            style={{ cursor: 'pointer' }}
                          />
                          <text
                            fill="#18181B"
                            strokeWidth="0"
                            x={0}
                            y={30}
                            textAnchor="middle"
                            style={{ fontSize: '12px', fontWeight: 'bold' }}
                          >
                            {nodeDatum.name}
                          </text>
                          {nodeDatum.attributes && (
                            <text
                              fill="#52525B"
                              strokeWidth="0"
                              x={0}
                              y={45}
                              textAnchor="middle"
                              style={{ fontSize: '10px' }}
                            >
                              {Object.entries(nodeDatum.attributes).map(([key, value]) =>
                                `${key}: ${value}`
                              ).join(' | ')}
                            </text>
                          )}
                        </g>
                      );
                    }}
                  />
                </div>
              ) : (
                <div style={{ textAlign: 'center', padding: '50px', color: '#A1A1AA' }}>
                  暂无执行计划数据
                </div>
              )}
            </Card>

            {/* PEV2 可视化 */}
            {selectedPlan && (
              <Card title="PEV2 可视化" style={{ marginTop: '16px' }}>
                <div style={{ width: '100%', height: '400px', border: '1px solid #E5E7EB' }}>
                  <iframe
                    src={`/pev2.html?plan=${encodeURIComponent(JSON.stringify(selectedPlan.nodes.map(node => node.raw_data)))}&query=${encodeURIComponent(selectedPlan.sql_content)}`}
                    width="100%"
                    height="100%"
                    style={{ border: 'none' }}
                    title="PEV2 可视化工具"
                  />
                </div>
              </Card>
            )}
          </>
        )}
      </Drawer>
    </div>
  );
};

export default PlanVisualizer;

// frontend-vue/src/pages/PlanVisualizer.vue
<template>
  <div class="page-container">
    <div class="page-header">
      <h2 class="page-title">执行计划</h2>
      <p class="page-description">查看和分析SQL查询执行计划</p>
    </div>

    <!-- 搜索和筛选功能合并到一个框内 -->
    <el-card class="card-container">
      <el-space direction="vertical" style="width: 100%">
        <!-- 第一行：数据集合选择 -->
        <el-space style="width: 100%">
          <span>选择数据集合:</span>
          <el-select
            v-model="selectedCollection"
            @change="handleCollectionChange"
            style="width: 200px"
            :disabled="!collections"
          >
            <el-option
              v-for="collection in collections?.collections"
              :key="collection"
              :label="collection"
              :value="collection"
            />
          </el-select>
        </el-space>
        
        <!-- 第二行：搜索和筛选功能 -->
        <el-space style="width: 100%">
          <span>搜索查询:</span>
          <el-input
            v-model="searchQuery"
            placeholder="输入SQL关键字搜索"
            style="width: 200px"
            clearable
          />
          
          <el-select
            v-model="searchStatus"
            style="width: 150px"
          >
            <el-option label="全部状态" value="all" />
            <el-option label="成功" value="success" />
            <el-option label="失败" value="error" />
          </el-select>
          
          <el-button
            type="primary"
            @click="handleSearch"
            :disabled="!selectedCollection"
          >
            搜索
          </el-button>
          
        </el-space>
      </el-space>
    </el-card>

    <el-alert
      v-if="error"
      title="错误"
      :description="error"
      type="error"
      style="margin-bottom: 24px"
    />

    <!-- 计划列表 -->
    <el-card>
      <el-table
        :data="plans"
        row-key="_id"
        v-loading="loading"
        border
        resizable
        :default-sort="{ prop: 'execution_time_ms', order: 'descending' }"
      >
        <el-table-column
          prop="sql_content"
          label="SQL内容"
          min-width="200"
          show-overflow-tooltip
          resizable
        >
          <template #default="{ row }">
            <div class="sql-content">
              {{ row.sql_content }}
            </div>
          </template>
        </el-table-column>
        
        <el-table-column
          prop="execution_time_ms"
          label="执行时间"
          width="120"
          sortable
          resizable
        >
          <template #default="{ row }">
            {{ row.execution_time_ms.toFixed(2) }}ms
          </template>
        </el-table-column>
        
        <el-table-column
          prop="row_count"
          label="返回行数"
          width="120"
          sortable
          resizable
        />
        
        <el-table-column
          prop="status"
          label="状态"
          width="100"
          resizable
        >
          <template #default="{ row }">
            <el-tag
              :type="row.status === 'success' ? 'success' : row.status === 'error' ? 'danger' : 'warning'"
            >
              {{ row.status === 'success' ? '成功' : row.status === 'error' ? '失败' : '未知' }}
            </el-tag>
          </template>
        </el-table-column>
        
        <el-table-column
          prop="file_name"
          label="文件名"
          width="150"
          show-overflow-tooltip
          resizable
        />
        
        <el-table-column
          label="操作"
          width="100"
          fixed="right"
          resizable
        >
          <template #default="{ row }">
            <el-button
              type="primary"
              link
              @click="handleViewPlan(row)"
            >
              <el-icon><View /></el-icon>
              查看
            </el-button>
          </template>
        </el-table-column>
      </el-table>
      
      <!-- 分页组件 -->
      <div class="pagination-container">
        <el-pagination
          v-model:current-page="currentPage"
          v-model:page-size="pageSize"
          :page-sizes="[10, 20, 50, 100]"
          :total="total"
          layout="total, sizes, prev, pager, next, jumper"
          @size-change="handleShowSizeChange"
          @current-change="handlePageChange"
        />
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { View } from '@element-plus/icons-vue'
import { apiService } from '@/services/api'
import { useRouter } from 'vue-router'
import type { CollectionList, SQLExecutionRecord } from '@/types'

const router = useRouter()
const collections = ref<CollectionList | null>(null)
const selectedCollection = ref<string>('')
const plans = ref<SQLExecutionRecord[]>([])
const loading = ref(false)
const error = ref<string>('')
const currentPage = ref(1)
const pageSize = ref(20)
const total = ref(0)

// 搜索相关状态
const searchQuery = ref('')
const searchStatus = ref<'all' | 'success' | 'error'>('all')

// 加载集合列表
onMounted(async () => {
  try {
    const data = await apiService.getCollections()
    collections.value = data
    if (data.collections.length > 0) {
      selectedCollection.value = data.collections[0]
    }
  } catch (err: any) {
    error.value = '加载集合列表失败'
  }
})

// 加载计划列表
watch([selectedCollection, currentPage, searchQuery, searchStatus], async () => {
  if (selectedCollection.value) {
    await loadPlans()
  }
})

const loadPlans = async () => {
  loading.value = true
  error.value = ''
  try {
    console.log('正在加载计划列表，集合:', selectedCollection.value, '搜索:', searchQuery.value, '状态:', searchStatus.value)
    
    let data
    if (searchQuery.value || searchStatus.value !== 'all') {
      // 使用搜索API
      const filters: any = {}
      if (searchQuery.value) {
        filters.q = searchQuery.value
      }
      if (searchStatus.value !== 'all') {
        filters.status = searchStatus.value
      }
      data = await apiService.searchPlans(selectedCollection.value, filters, currentPage.value, pageSize.value)
    } else {
      // 使用普通获取API
      data = await apiService.getPlans(selectedCollection.value, currentPage.value, pageSize.value)
    }
    
    console.log('计划列表加载成功:', data)
    plans.value = data.items
    total.value = data.total
  } catch (err: any) {
    console.error('加载计划列表失败:', err)
    error.value = `加载计划列表失败: ${err.response?.data?.detail || err.message || '未知错误'}`
  } finally {
    loading.value = false
  }
}

const handlePageChange = (page: number, size?: number) => {
  currentPage.value = page
  if (size && size !== pageSize.value) {
    pageSize.value = size
  }
}

const handleShowSizeChange = (size: number) => {
  pageSize.value = size
  currentPage.value = 1
}

const handleCollectionChange = (value: string) => {
  selectedCollection.value = value
  currentPage.value = 1
}

const handleSearch = async () => {
  if (selectedCollection.value) {
    currentPage.value = 1
    await loadPlans()
  }
}

const handleViewPlan = (record: SQLExecutionRecord) => {
  try {
    console.log('=== 开始查看执行计划 ===')
    console.log('record数据:', record)
    console.log('record._id:', record._id)
    console.log('selectedCollection.value:', selectedCollection.value)
    
    // 验证必要的数据字段
    if (!record._id || record._id.trim() === '') {
      ElMessage.error('该数据条目缺少有效的ID，无法查看执行计划')
      return
    }
    
    if (!selectedCollection.value) {
      ElMessage.error('缺少集合信息，无法查看执行计划')
      return
    }
    
    if (record.status === 'error') {
      ElMessage.warning('该查询执行失败，无法查看执行计划')
      return
    }
    
    // 跳转到PEV2Viewer页面，传递必要的参数
    router.push({
      name: 'PEV2Viewer',
      query: {
        id: record._id.trim(),
        collection: selectedCollection.value
      }
    })
    
    console.log('=== 跳转到PEV2Viewer页面 ===')
    
  } catch (err: any) {
    console.error('=== 查看计划失败 ===')
    console.error('错误类型:', typeof err)
    console.error('错误信息:', err)
    console.error('错误堆栈:', (err as Error).stack)
    ElMessage.error('跳转到查询计划可视化页面失败: ' + (err as Error).message)
  }
}
</script>

<style scoped>
.page-container {
  padding: 0;
}

.page-header {
  margin-bottom: 24px;
}

.page-title {
  margin: 0;
  color: #18181b;
}

.page-description {
  color: #a1a1aa;
  margin-top: 8px;
}

.card-container {
  margin-bottom: 24px;
}

.sql-content {
  max-width: 400px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  word-break: break-all;
}

/* 表格样式优化 */
.el-table {
  --el-table-border-color: #ebeef5;
  --el-table-header-bg-color: #f5f7fa;
}

.el-table th {
  background-color: var(--el-table-header-bg-color);
  font-weight: 600;
}

.el-table td {
  padding: 8px 0;
}

/* 表格列宽调整样式 */
.el-table .cell {
  word-break: break-word;
  white-space: pre-wrap;
}

.el-table .el-table__header-wrapper th {
  position: relative;
}

.el-table .el-table__header-wrapper th .cell {
  padding-right: 20px;
}

/* 拖拽调整列宽时的样式 */
.el-table--border .el-table__cell {
  border-right: 1px solid var(--el-table-border-color);
}

.el-table--enable-row-hover .el-table__body tr:hover > td {
  background-color: var(--el-table-row-hover-bg-color);
}

.pagination-container {
  display: flex;
  justify-content: center;
  margin-top: 16px;
}

</style>
